#pragma once
#include "PluginMain.h"


//CBTYPE bType // event type, one of the `cbType` CB_* values listed above
//PLUG_EXPORT void * callbackInfo // pointer to a structure of information

PLUG_EXPORT void CBINITDEBUG( CBTYPE bType, PLUG_CB_INITDEBUG *callbackInfo );

PLUG_EXPORT void CBSTOPDEBUG(CBTYPE bType, PLUG_CB_STOPDEBUG *callbackInfo);

PLUG_EXPORT void CBCREATEPROCESS(CBTYPE bType, PLUG_CB_CREATEPROCESS * callbackInfo);

PLUG_EXPORT void CBEXITPROCESS(CBTYPE bType, PLUG_CB_EXITPROCESS * callbackInfo);

PLUG_EXPORT void CBEXITTHREAD(CBTYPE bType, PLUG_CB_CREATETHREAD * callbackInfo);

PLUG_EXPORT void CBSYSTEMBREAKPOINT(CBTYPE bType, PLUG_CB_SYSTEMBREAKPOINT * callbackInfo);

PLUG_EXPORT void CBLOADDLL(CBTYPE bType, PLUG_CB_LOADDLL * callbackInfo);

PLUG_EXPORT void CBUNLOADDLL(CBTYPE bType, PLUG_CB_UNLOADDLL * callbackInfo);

PLUG_EXPORT void CBOUTPUTDEBUGSTRING(CBTYPE bType, PLUG_CB_OUTPUTDEBUGSTRING * callbackInfo);

PLUG_EXPORT void CBEXCEPTION(CBTYPE bType, PLUG_CB_EXCEPTION * callbackInfo);

PLUG_EXPORT void CBBREAKPOINT(CBTYPE bType, PLUG_CB_BREAKPOINT * callbackInfo);

PLUG_EXPORT void CBPAUSEDEBUG(CBTYPE bType, PLUG_CB_PAUSEDEBUG * callbackInfo);

PLUG_EXPORT void CBRESUMEDEBUG(CBTYPE bType, PLUG_CB_RESUMEDEBUG * callbackInfo);

PLUG_EXPORT void CBSTEPPED(CBTYPE bType, PLUG_CB_STEPPED * callbackInfo);

PLUG_EXPORT void CBATTACH(CBTYPE bType, PLUG_CB_ATTACH * callbackInfo);

PLUG_EXPORT void CBDETACH(CBTYPE bType, PLUG_CB_DETACH * callbackInfo);

PLUG_EXPORT void CBDEBUGEVENT(CBTYPE bType, PLUG_CB_DEBUGEVENT * callbackInfo);

PLUG_EXPORT void CBMENUENTRY(CBTYPE bType, PLUG_CB_MENUENTRY * callbackInfo);

PLUG_EXPORT void CBWINEVENT(CBTYPE bType, PLUG_CB_WINEVENT * callbackInfo);

PLUG_EXPORT void CBWINEVENTGLOBAL(CBTYPE bType, PLUG_CB_WINEVENTGLOBAL * callbackInfo);

PLUG_EXPORT void CBSAVEDB(CBTYPE bType, PLUG_CB_LOADSAVEDB * callbackInfo);

//PLUG_EXPORT void CBLOADDB(CBTYPE bType, PLUG_CB_LOADLOADDB * callbackInfo);


